baseURL = "https://guardianhubx.com/"
title = "GuardianHubX"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true

[languages]

  [languages.es]
    languageName = "Español"
    weight = 1
    contentDir = "content/es"
    title = "GuardianHubX - Seguridad Cibernética"

  [languages.ca]
    languageName = "Català"
    weight = 2
    contentDir = "content/ca"
    title = "GuardianHubX - Ciberseguretat"

  [languages.en]
    languageName = "English"
    weight = 3
    contentDir = "content/en"
    title = "GuardianHubX - Cybersecurity"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[params]
  description = "Soluciones avanzadas de ciberseguridad para empresas y autónomos"
  author = "GuardianHubX"

[taxonomies]
  category = "categories"
  tag = "tags"